# Generated by Django 3.2.1 on 2021-05-09 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210507_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='disp_date_limit',
            new_name='publication_date',
        ),
    ]
